### ISSUE TITLE
Замечания к стандарту

### ISSUE THREAD

**Issue by DenzeL2004** [B05-232/plug-standard#18]
1. Почему параметр delta_time в TickEvent типа double. У нас все равно delta_time считается в миллисекундах.
2. Изменит структуру plug::Texture. На данный момент с ней неудобно и небезопасно работать (выделяется память при помощи new, но потом нигде не регулируем, что память была освобождена).
3. Раньше в стандарте были методы set/getFocus - стоит ли их вернуть?

**Comment by DenzeL2004** [comment]
добавить plug::RenderTarget метод display()

**Comment by DenzeL2004** [comment]
Добавить в RenderTarget метод, позволяющий писать текст

**Comment by Sigmarik** [comment]
Предлагаю разбить диалог в этом issue на несколько (по отдельному issue на правку). Можно даже внести отдельный label для замечаний/предложений по стандарту.
