### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by DarkSoulEater** [B05-232/plug-standard#36]
I propose to make the Texture store an array of colors and delete it in the destructor.

**Comment by MeerkatBoss** [comment]
Does this mean that we are only going to keep the constructor that allocates the memory for the array? Or does this mean that the pointer passed to constructor is always going to be deleted in the destructor?

**Comment by MeerkatBoss** [comment]
Also, in any case, the field `plug::Texture::data` should have the type `plug::Color* const`, not `const plug::Color*`

**Comment by DarkSoulEater** [comment]
I think we can leave the constructor to which Color* data is passed. just copy the data rather than saving the pointer.

**Comment by DarkSoulEater** [comment]
> Also, in any case, the field `plug::Texture::data` should have the type `plug::Color* const`, not `const plug::Color*`

I probably agree

**Comment by MeerkatBoss** [comment]
> just copy the data rather than saving the pointer.

Wouldn't it be wasteful if we store data somewhere else and use `plug::Texture` only to pass this data somewhere else? BTW, in this case we probably don't want this data to be `delete`-ed in destructor.

**Comment by DarkSoulEater** [comment]
Storing somewhere else would definitely be faster, but you have to think about how convenient this storage will be. Copying is time-consuming, but simple. I propose to leave the issue of this opimitation to the second standard. Now use simple copy and delete in destructor always.

**Comment by DarkSoulEater** [comment]
My use now: return Texture(image.getSize().x, image.getSize().y, (Color*)image.getPixelsPtr());
But image is local function var and if there is no copying, there may be problems.

**Comment by DarkSoulEater** [comment]
Fixed
