### ISSUE TITLE
Null virtual destructor 

### ISSUE THREAD

**Issue by DarkSoulEater** [B05-232/plug-standard#38]
It is necessary to make all virtual destructors equal to {}, and not = 0

**Comment by DarkSoulEater** [comment]
= default is bad too

**Comment by MeerkatBoss** [comment]
> = default is bad too

Why though? It's the same as empty destructor, isn't it?

**Comment by DarkSoulEater** [comment]
> > = default is bad too
> 
> Why though? It's the same as empty destructor, isn't it?

I'm not sure if it's always like this.
I think {} is clearer.  Moreover, =default seemed to cause some kind of compilation error for me.

**Comment by MeerkatBoss** [comment]
I think [this section](https://en.cppreference.com/w/cpp/language/destructor#Trivial_destructor) says that `default`-ed destructor is exactly what we need - a destructor that performs no action. `= default` seems clearer for me, and it seems to be interchangeable with `{}`, so I think we can use both.
